---
- name: copy_file
  hosts: all
  tasks:
    - name: copy_file
      copy:
        src: /root/newfile
        dest: /home/ubuntu
    - name: packaging_module
      apt:
        name: git
        state: latest
      when: ansible_os_family == "Debian"
