---
- name: copyplaybook
  hosts: all
  become: yes
  tasks: 
    - name: copy_file
      copy:
        src: /root/newfile
        dest: /home/newuser
    - name: packaging_module
      apt: 
        name: git
        state: latest
      
